/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service health probe
     * @description Reports combined health status of the service and its runtime
     *     dependencies (database, cache, realtime bus).
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/realtime/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a short-lived Centrifugo connection token
     * @description Mints a short-lived HMAC-signed JWT that the client can use to connect
     *     to Centrifugo. Requires an active Better Auth session (cookie on web,
     *     bearer token on mobile).
     */
    post: operations['issueRealtimeToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string|null} */
    DependencyStatus: 'ok' | 'degraded' | 'down' | null;
    HealthStatus: {
      status: components['schemas']['DependencyStatus'];
      /** @description Semantic version of the running backend build */
      version: string | null;
      /** @description Seconds since the backend process started */
      uptimeSeconds: number;
      dependencies: {
        db: components['schemas']['DependencyStatus'];
        redis: components['schemas']['DependencyStatus'];
        centrifugo: components['schemas']['DependencyStatus'];
      };
    };
    /** @description RFC 9457 problem details */
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string | null;
      title: string | null;
      /** Format: int32 */
      status: number;
      detail?: string | null;
      instance?: string | null;
      code?: string | null;
    };
    RealtimeToken: {
      /** @description Short-lived HMAC-signed JWT for Centrifugo */
      token: string | null;
      /**
       * Format: date-time
       * @description ISO-8601 instant when the token expires
       */
      expiresAt: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service and all dependencies are operational */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
      /** @description One or more dependencies are degraded or down */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  issueRealtimeToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RealtimeToken'];
        };
      };
      /** @description No active session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
