/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service health probe
     * @description Reports health status of the service and its database dependency.
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Server-Sent Events stream of the caller's item and job updates
     * @description Long-lived `text/event-stream` connection. Each message is a JSON
     *     payload `{ "type": ..., "data": ... }` describing an item or job change
     *     for the authenticated user. A periodic `ping` event acts as a heartbeat.
     *     Requires an active Better Auth session.
     */
    get: operations['streamEvents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string|null} */
    DependencyStatus: 'ok' | 'degraded' | 'down' | null;
    HealthStatus: {
      status: components['schemas']['DependencyStatus'];
      /** @description Semantic version of the running backend build */
      version: string | null;
      /** @description Seconds since the backend process started */
      uptimeSeconds: number;
      dependencies: {
        db: components['schemas']['DependencyStatus'];
      };
    };
    /** @description RFC 9457 problem details */
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string | null;
      title: string | null;
      /** Format: int32 */
      status: number;
      detail?: string | null;
      instance?: string | null;
      code?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service and all dependencies are operational */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
      /** @description One or more dependencies are degraded or down */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  streamEvents: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description An open event stream. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      /** @description No active session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
