/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health probe
         * @description Reports health status of the service and its database dependency.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of the caller's item and job updates
         * @description Long-lived `text/event-stream` connection. Each message is a JSON
         *     payload `{ "type": ..., "data": ... }` describing an item or job change
         *     for the authenticated user. A periodic `ping` event acts as a heartbeat.
         *     Requires an active Better Auth session.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List saved items with optional filtering
         * @description Returns a cursor-paginated list of the authenticated user's saved items. Supports filtering by read state, tag, favourite flag, and full-text search.
         */
        get: operations["listItems"];
        put?: never;
        /**
         * Save a new URL to the reading list
         * @description Creates an item with status `pending`. A background job is dispatched to fetch metadata (title, excerpt, images). The item becomes `ready` or `failed` asynchronously.
         */
        post: operations["saveItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Fetch a single item by ID
         * @description Returns the full item record for the given ID, scoped to the authenticated user.
         */
        get: operations["getItem"];
        put?: never;
        post?: never;
        /**
         * Permanently delete an item
         * @description Permanently removes the item and all its tag associations. This operation cannot be undone.
         */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        /**
         * Update read state or favourite flag on an item
         * @description Partially updates an item. At least one of `readState` or `favorite` must be provided. Setting `readState` to `read` for the first time records `readAt`.
         */
        patch: operations["updateItem"];
        trace?: never;
    };
    "/api/v1/items/{id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a tag to an item (creates the tag if it does not exist)
         * @description Attaches a tag to the item by slug. If the tag does not yet exist for this user it is created automatically and a slug is derived from the provided name.
         */
        post: operations["addItemTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/tags/{tagSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
                /** @description Tag slug to remove */
                tagSlug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a tag from an item
         * @description Detaches the specified tag from the item. The tag record itself is not deleted; use `DELETE /api/v1/tags/{id}` for that.
         */
        delete: operations["removeItemTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/article": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get extracted article content for an item
         * @description Returns the full extracted article body (HTML and plain text) for the given item. Returns 404 if the article has not been extracted yet.
         */
        get: operations["getArticle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger article content extraction for an item
         * @description Idempotent: always returns 202 and (re)starts extraction, replacing any
         *     existing article. No request body. Safe to call in any `extractStatus`
         *     state (`none`, `failed`, or `ready`). The item's `extractStatus`
         *     transitions to `extracting` immediately and becomes `ready` or `failed`
         *     asynchronously.
         */
        post: operations["extractArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        /**
         * List all highlights on an item
         * @description Returns all highlights the authenticated user has created on the given item.
         */
        get: operations["listHighlights"];
        put?: never;
        /**
         * Create a highlight on an item
         * @description Saves a new text highlight (with optional note and color) on the given item.
         */
        post: operations["createHighlight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/items/{id}/image/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
                /**
                 * @description Opaque image key assigned by the extraction job. Clients MUST NOT
                 *     construct this value: the extraction job rewrites `<img src>` URLs
                 *     inside `Article.contentHtml` to `/api/v1/items/{id}/image/{key}`
                 *     paths, so clients only ever follow keys that already appear in the
                 *     article HTML.
                 */
                key: string;
            };
            cookie?: never;
        };
        /**
         * Retrieve a cached image associated with an item
         * @description Streams a cached image file that was downloaded during article extraction. Returns 404 if the image key does not exist or is not owned by the authenticated user.
         */
        get: operations["getItemImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/highlights/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Highlight ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a highlight
         * @description Permanently removes the highlight. This operation cannot be undone.
         */
        delete: operations["deleteHighlight"];
        options?: never;
        head?: never;
        /**
         * Update a highlight's note or color
         * @description Partially updates a highlight. At least one of `note` or `color` must be provided.
         */
        patch: operations["updateHighlight"];
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all tags for the authenticated user
         * @description Returns every tag that belongs to the authenticated user, ordered by name, with a count of associated items.
         */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a tag and remove it from all items
         * @description Permanently deletes the tag and cascades removal from all items that carry it. This operation cannot be undone.
         */
        delete: operations["deleteTag"];
        options?: never;
        head?: never;
        /**
         * Rename a tag (updates name; slug is re-derived server-side)
         * @description Updates the display name of a tag. The slug is automatically re-derived from the new name server-side.
         */
        patch: operations["renameTag"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string|null} */
        DependencyStatus: "ok" | "degraded" | "down" | null;
        HealthStatus: {
            status: components["schemas"]["DependencyStatus"];
            /** @description Semantic version of the running backend build */
            version: string | null;
            /** @description Seconds since the backend process started */
            uptimeSeconds: number;
            dependencies: {
                db: components["schemas"]["DependencyStatus"];
            };
        };
        /** @description RFC 9457 problem details */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string | null;
            title: string | null;
            /** Format: int32 */
            status: number;
            detail?: string | null;
            instance?: string | null;
            code?: string | null;
        };
        /**
         * @description Processing status of the item's metadata extraction job
         * @enum {string}
         */
        ItemStatus: "pending" | "ready" | "failed";
        /**
         * @description The user's read progress for an item
         * @enum {string}
         */
        ReadState: "unread" | "read" | "archived";
        Item: {
            /** @description Unique item ID (cuid) */
            id: string;
            /**
             * Format: uri
             * @description Original URL submitted by the user
             */
            url: string;
            /**
             * Format: uri
             * @description Canonical URL resolved during metadata extraction
             */
            canonicalUrl?: string | null;
            /** @description Page title */
            title?: string | null;
            /** @description Name of the publishing site */
            siteName?: string | null;
            /** @description Short plain-text excerpt */
            excerpt?: string | null;
            /**
             * Format: uri
             * @description Hero/lead image URL
             */
            leadImageUrl?: string | null;
            /**
             * Format: uri
             * @description Site favicon URL
             */
            faviconUrl?: string | null;
            status: components["schemas"]["ItemStatus"];
            extractStatus: components["schemas"]["ExtractStatus"];
            readState: components["schemas"]["ReadState"];
            /** @description Whether the item is marked as a favourite */
            favorite: boolean;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the item was saved
             */
            savedAt: string;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the item was first marked read
             */
            readAt?: string | null;
            /** @description Slugs of tags attached to this item */
            tags: string[];
        };
        ItemList: {
            items: components["schemas"]["Item"][];
            /** @description Opaque cursor for the next page; null when no more pages */
            nextCursor: string | null;
        };
        Tag: {
            /** @description Unique tag ID (cuid) */
            id: string;
            /** @description Human-readable tag name (original casing) */
            name: string;
            /** @description URL-safe lowercase slug derived from name */
            slug: string;
            /** @description Number of items carrying this tag */
            count: number;
        };
        TagList: {
            tags: components["schemas"]["Tag"][];
        };
        SaveItemRequest: {
            /**
             * Format: uri
             * @description URL to save
             */
            url: string;
            /** @description Optional tag slugs to attach immediately */
            tags?: string[];
        };
        /** @description At least one of `readState` or `favorite` must be provided. */
        UpdateItemRequest: {
            readState?: components["schemas"]["ReadState"];
            /** @description Set or clear the favourite flag */
            favorite?: boolean;
        };
        AddTagRequest: {
            /** @description Tag name or slug to add (created if absent) */
            tag: string;
        };
        RenameTagRequest: {
            /** @description New display name for the tag */
            name: string;
        };
        /**
         * @description Status of the article content extraction job for an item
         * @enum {string}
         */
        ExtractStatus: "none" | "extracting" | "ready" | "failed";
        /**
         * @description Response body returned when an extraction job is accepted (202).
         * @example {
         *       "extractStatus": "extracting"
         *     }
         */
        ExtractAccepted: {
            extractStatus: components["schemas"]["ExtractStatus"];
        };
        Article: {
            /** @description Full article body as HTML */
            contentHtml: string;
            /** @description Full article body as plain text (HTML stripped) */
            contentText: string;
            /** @description Number of words in the extracted article */
            wordCount: number;
            /** @description Estimated reading time in minutes */
            readingTimeMin: number;
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the extraction completed
             */
            extractedAt: string;
        };
        /**
         * @description Color label for a text highlight
         * @enum {string}
         */
        HighlightColor: "yellow" | "green" | "blue" | "pink";
        Highlight: {
            /** @description Unique highlight ID (cuid) */
            id: string;
            /** @description ID of the item this highlight belongs to (cuid) */
            itemId: string;
            /** @description The exact text that was highlighted */
            quote: string;
            /** @description Short text immediately before the highlighted quote (for anchor context) */
            prefix: string;
            /** @description Short text immediately after the highlighted quote (for anchor context) */
            suffix: string;
            /** @description Optional reader note attached to the highlight */
            note?: string | null;
            color: components["schemas"]["HighlightColor"];
            /**
             * Format: date-time
             * @description ISO-8601 timestamp when the highlight was created
             */
            createdAt: string;
        };
        HighlightList: {
            highlights: components["schemas"]["Highlight"][];
        };
        CreateHighlightRequest: {
            /** @description The exact text that was highlighted */
            quote: string;
            /** @description Short text immediately before the quote (for anchor context) */
            prefix?: string;
            /** @description Short text immediately after the quote (for anchor context) */
            suffix?: string;
            /**
             * @description Optional reader note to attach. To clear a note on an existing
             *     highlight, use `PATCH /highlights/{id}` with `note: null` —
             *     create only sets a note, it cannot null one.
             */
            note?: string;
            color?: components["schemas"]["HighlightColor"];
        };
        /** @description At least one of `note` or `color` must be provided. */
        UpdateHighlightRequest: {
            /** @description Updated reader note; set to null to clear */
            note?: string | null;
            color?: components["schemas"]["HighlightColor"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and all dependencies are operational */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description One or more dependencies are degraded or down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description No active session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listItems: {
        parameters: {
            query?: {
                /** @description Filter by read state */
                readState?: components["schemas"]["ReadState"];
                /** @description Filter by tag slug */
                tag?: string;
                /** @description Filter to favourites only */
                favorite?: boolean;
                /** @description Full-text search query */
                q?: string;
                /** @description Opaque cursor for the next page */
                cursor?: string;
                /** @description Number of items to return (1–100, default 20) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    saveItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveItemRequest"];
            };
        };
        responses: {
            /** @description Item created (metadata extraction is asynchronous; initial status is `pending`) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Request body invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemRequest"];
            };
        };
        responses: {
            /** @description Updated item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Request body invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    addItemTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagRequest"];
            };
        };
        responses: {
            /** @description Item with updated tag list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Request body invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    removeItemTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
                /** @description Tag slug to remove */
                tagSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag removed from item */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extracted article content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Article not yet extracted or item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    extractArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Extraction job accepted; extractStatus is now `extracting` */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractAccepted"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listHighlights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of highlights */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createHighlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHighlightRequest"];
            };
        };
        responses: {
            /** @description Highlight created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Highlight"];
                };
            };
            /** @description Request body invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Item not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getItemImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Item ID (cuid) */
                id: string;
                /**
                 * @description Opaque image key assigned by the extraction job. Clients MUST NOT
                 *     construct this value: the extraction job rewrites `<img src>` URLs
                 *     inside `Article.contentHtml` to `/api/v1/items/{id}/image/{key}`
                 *     paths, so clients only ever follow keys that already appear in the
                 *     article HTML.
                 */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Raw cached image bytes. The `Content-Type` header reflects the
             *     original media type of the image. No example is representable for
             *     binary content; follow the URL directly in a browser or image view.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                    "application/octet-stream": string;
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Image not found or not owned by the authenticated user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteHighlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Highlight ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Highlight deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Highlight not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateHighlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Highlight ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateHighlightRequest"];
            };
        };
        responses: {
            /** @description Updated highlight */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Highlight"];
                };
            };
            /** @description Request body invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Highlight not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tags with item counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagList"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    renameTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tag ID (cuid) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTagRequest"];
            };
        };
        responses: {
            /** @description Tag renamed successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request body invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Not authenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Tag not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
