/* eslint-disable */
// ─────────────────────────────────────────────────────────────────────────────
// Generated by `pnpm --filter @app/specs codegen` from
// `packages/specs/asyncapi/centrifugo.yaml`. DO NOT EDIT BY HAND — your
// changes will be overwritten on next codegen. Edit the AsyncAPI document
// instead.
// ─────────────────────────────────────────────────────────────────────────────

export interface HealthUpdate {
  status: 'ok' | 'degraded' | 'down';
  changedAt: string;
  reason?: string;
}

export type RealtimeChannel = 'system:health';

export interface RealtimeChannelPayloadMap {
  'system:health': HealthUpdate;
}

export type RealtimeChannelPayload<C extends RealtimeChannel> = RealtimeChannelPayloadMap[C];
